export default [
	"That’s an interesting approach… if you’re aiming for confusion.",
	"You call that logic? My grandma’s knitting patterns make more sense.",
	"I see what you’re doing. The computer, however, doesn’t.",
	"Is this part of your grand plan to confuse the compiler?",
	"Keep going! At this rate, you’ll solve it by next year.",
	"That’s one way to keep the CPU busy. Not the right way, but a way.",
	"Just a few hundred more lines of code and you might have something.",
	"I’ve seen infinite loops that end faster than this.",
	"It’s like watching a mystery unfold… even you don’t know the ending.",
	"I’d help you out, but I’m kind of enjoying this trainwreck.",
	"You're not stuck... you're just exploring all the wrong paths.",
	"The debugger called, even it’s confused.",
	"Nice try! I’m sure someone, somewhere, would be proud of that attempt.",
	"I've seen code, and then there's... whatever this is.",
	"I can see the effort, but the solution? Not so much.",
	"This might take longer than your last software update.",
	"At least you're consistent... consistently off-track.",
	"I guess you're going for the ‘trial and error’ method. Heavy on the error.",
	"Just throw a 'console.log' in there, maybe it'll explain itself.",
	"I’ve seen random number generators with more predictable output.",
	"You're trying so hard, the keyboard might start sweating.",
	"If coding were easy, everyone would still be doing it better than this.",
	"Wow, you're creating more problems than you're solving. Impressive.",
	"Is this a puzzle or performance art? Because I'm not sure anymore.",
	"Keep going! The bugs are having the time of their lives.",
	"You're almost there! Just kidding, you’re not even close.",
	"That code’s so broken, even Stack Overflow gave up on it.",
	"I’d give you a hint, but I’m curious to see where this disaster leads.",
	"You’re really testing the boundaries of what 'possible' means in code.",
	"If confusion was your goal, congrats, you're nailing it.",
	"It’s like you’re writing in a language no one, not even the compiler, understands.",
	"Don't worry, even professionals break things this badly… sometimes.",
	"Are you trying to code or create abstract art? Because it’s a little hard to tell.",
	"You're coding like your keyboard is on a vacation.",
	"You might want to check if your keyboard has a ‘delete’ key.",
	"This looks like a ‘try-catch’ block without the ‘try’.",
	"You're one semicolon away from a breakthrough… or a meltdown.",
	"If I had a dollar for every bug in your code, I could retire early.",
	"Are you sure you’re not just trying to write a novel instead of code?",
	"Looks like your code is taking the scenic route… very scenic.",
	"You’re making ‘buggy’ look like an art form.",
	"At this rate, you’ll finish debugging by the time the next ice age hits.",
	"I’ve seen clearer logic in a game of Twister.",
	"You’re on the right track... if the destination is ‘total chaos’!",
	"This is like watching someone try to solve a Rubik’s Cube blindfolded.",
	"You’re really pushing the limits of what ‘functioning code’ means.",
	"I didn’t know ‘broken’ could be a style choice!",
	"You’ve got this! Just remember, the keyboard isn’t a punching bag.",
	"I’d give you a standing ovation, but I’m afraid I might trip over the bugs.",
	"Are you sure this isn’t a secret code for ‘please help me’?",
	"It’s like your code took a wrong turn at Albuquerque.",
	"Your code and a riddle have one thing in common: they both make no sense.",
	"The only thing missing from this code is the ‘;’ at the end… and maybe some sanity.",
	"This code is more tangled than my headphones after a long day.",
	"I’d say this is a masterpiece, but I don’t want to insult real art.",
	"It’s like your code is auditioning for a role in a horror movie.",
	"You’re proving that even computers have their limits.",
	"Every line you write adds more mystery to the plot.",
	"You’re a pioneer of chaos theory in programming.",
	"I didn’t realize you were coding in Morse code—so many dots and dashes!",
	"The code looks great… from a distance. A very, very far distance.",
	"I see your code is inspired by modern art: confusing and abstract.",
	"You're so close! Just a few wrong turns away from the right answer.",
	"If you keep this up, the next update might just be a soft reboot.",
	"Congratulations! You've successfully rewritten the definition of ‘inefficient’.",
	"I’d call this a unique approach, but ‘unique’ implies some thought.",
	"You’ve got the spirit! Just need a bit more… guidance… and maybe a map.",
	"Your code has more twists and turns than a season finale cliffhanger.",
	"Are you sure you didn’t mean to write a horror story instead of code?",
	"This is what happens when code and chaos become best friends.",
	"If there were a competition for the most creative way to fail, you’d win.",
	"Your debugging skills are remarkable—remarkably absent!"
];
