import type { Metadata } from "next";
import { Navigation } from "../components/dynamic-nav";
import localFont from "next/font/local";
import Providers from "./Providers";
import "./globals.css";
import Authenticate from "./Authenticate";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-white bg-black`}>
        <Providers>
          <Authenticate>
            {children}
          </Authenticate>
        </Providers>
      </body>
    </html>
  );
}
