import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "./Providers";
import "./globals.css";
import Authenticate from "./Authenticate";
import { Slide, toast, ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { Suspense } from "react";
import Progressbar from "@/components/Progressbar";
import BottomNavigation from "@/components/BottomNavigation";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <body className={`kanit-regular overflow-hidden min-h-screen antialiased text-white bg-gradient-to-br`} style={{
        background: 'linear-gradient(45deg, rgb(0, 0, 0), rgb(13, 12, 12), rgb(0, 0, 0))',
      }
      } >

        <Providers>
          <Authenticate>
            <Progressbar />
            {children}
            <ToastContainer
              position="bottom-right"
              transition={Slide}
              autoClose={1000}
              hideProgressBar
              theme="dark"
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />

          </Authenticate>
        </Providers>
      </body>
    </html>
  );
}
